# Generated via: 
# kubeseal --scope namespace-wide --namespace daily-questions --controller-namespace bitnami --controller-name sealed-secrets -o yaml < local-config.yaml > kubernetes/secret.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: daily-questions-config
  namespace: daily-questions
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true" # The secret can be renamed within the provided namespace.
spec:
  encryptedData:
    daily-conf.yaml: AgBdWM/MlKufK0AhVHT7Qw2+bOfl+l1+ZKZEihYv0gU/EHQ1w4NBRqvlLKwxvUkFzbmLYnO27ycf54v6LdT6JgLNCjet/VwvssWngoTi6dwh6xjD0dmMyWr74okVpYS7AF4anAI8ZSOGptcYwfWhjtp9J5oOcUlS223VySsqaH8341bFKfNQaX0u03ECO2q+4xa+2Y5kKnpYpR6o4KLoUglvzsWNsQKCEeDESDdVGkT/NjAfzcel05xE9aePkUF0pbbBuN1eWiPIu/Ypm/jBOoWiuq0S54bWGwq9mM+uvUfhfkDEg0GFxSmBFbQrSKuvuWhUCuoJNZYdIYrOTaYMK3hOjdcEMhnoaAzxPXJfJAprs0G+NmZsmrPsEBCP70X6XYnWHz5bZ+MtERpZY1elKt+USHgqfOIlh2UsJqGZiI9pBigSTO+Xubi2GEFc7W2eVltI8aG+1trtlZQEWbQNIkaKZiuB0Tir3sKMW/akSMEApFnqTeXT7hEct9lcw32gvNVbHBwYvE11Jp3Yk4CEFljnhRiTu4NMUQYM6yUhvII0WnO1jitsoVq+hCRiWOtNLK1SHXr18aj28wPCAs9LEQNT0hovI8pj33wxfzHviFPf+UA1eNyeHZKKPZMHJd/zw8UdrxT4NyHtsOD7SfIBQ/PZxlM8cz/fcXPx4wnG/8wkqka9UmLwiQ9dz233aCbvoTYw/vaSGml4ny68RL+Xnn21NxBuD/iy5gOVvu4tq348BuCe62ltb80id0eWgBmTqMcit7rTYKAE8ftlTE5BiyEZiYNQIuuNlYwngRfe6Dv+yKJSK1FHwPf6eq1t4SPF3/NM3d2m1MX3g7nf3vuMPL6HUHdkx/yskdx/8CqVzRmHKVJtLap5g1X6tu6zLLCzGYNpCzqTIZBukniHjwq3hJ3YxgjEf4f4IlAQ+vFtqfZBK0qCgPtIGwOuDqdhy84CmKg14CVCqb9P2CXmqk5+UMqrDOEkTWXr+MYSyPjV+dekSNQ34lUOzYOihpIYukDugPf2rPkyNfq8L4VBhE96WwYaJaLnizkuPCWFLxf6iIbviHQzcOQhh5zkJ6MvqRQSfTKwgiKeguFhjIE+t2wlnNGjzkMe34AFlMZnpQD5MYDREN+4Kae+SHgSgmV36qtq/TfpNSKvemD1xM6mHmCnip0ZAgrIClyCneKV0mMQiMIJvxyjYOqo4/F7rC1pUDicwX7yNLx8nDAqi0XsCZxidNk58e9gJIC8BpssJPXacIeFsmHKZVjOo/Djc3yUZzXFRfqPTMp0w4yK+5tpdaDOm0YnUqmwlmGhgMweIC9VnUXeu8u+hsdYwbqnz+Wb/uwZgR+GNOQm0yCSdQBfB0Tlp5bHAJ45k65OWrh1IwSWUzMW9q/gYQogUhoLuZk=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: daily-questions-config
      namespace: daily-questions
    type: Opaque