apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: daily-questions-config
  namespace: daily-questions
spec:
  encryptedData:
    daily-conf.yaml: AgAB7TxF1rrb3aKFWLZvFrR+0Ccz3iHLGRbKSRstbO99VWFmhJpmICD5IevA7J5NBOscA83Mo9fE4RqArBrjCOoI7njfkL0dO4QTpeoCTjJyDEQGky/W6Ajt1UTEpBxdbly4Mb7PIFf+ev1Uspytv92NJX7pVEqAxgcnUeFRNoDhiVDQtWgqb+YOPY6YxThLgRRUK4ka9Cc+nUrcg/19kV7M+tVtVfh1vBHFurwzEjAg3Ny6ETxdPcDCXtenf3gza62UFljxn8lJ18xJIjtM+Gyx7b8WZe1cSB2xsraSHH+zFMFWROYrJ28ESqIfrfXbSbo2JWBbo7xdG7ambkSzaeEdOxBjbnqxIaYo+FIvmv9Ufb0AhDV3j7995kH2kfyrZmqoSvCZHYTCLtkK7zZv/1dv2yd4PjlOs0Cau3+Z9P4cD2hc5D1pqYbT/DFiz7vAN7HzvASFaRu6ACM6lkDjI9a+iL+A67e+vYpDCbf9lKQL0XiYzbUw7ZmzSnj5ogZTKdPMh5HPSaB3zcnf9I3J3kXv3b7zqkiyoWiVU5iAQsZAKg2+KTVtyuFZFewBziiIGnPKgYHr3W9aXQZSaL7mTwwVI47wZqtRrQ84uk6bGmuB6SHFQZ11aBlwTERjSdLV6PRO0A9CGKDzezItUFXP41TaLeULh8K4G1fQnMjLrWeRM79c8HW6KRJWpWrhmlcLuQaEkq4cGAGstnv5efEZRX3KpsxTUwUFwTfuzPXRyKMFuppfuQmXf8o0trRxzR8aDX7/lwfPUIKZUfEi488Nl59rbVk27qELWz3mJOa0LczMTHlsogvgRPBDIpNTtgytiQTvkUkV7/5gq9Jz6O/pK5lI8+6pWDCEl32rbtXqDQc1x1TPNjFJtoTbG22HBPEXJxp/sneE8gzpy2t/GkYcqZiTCfpjkPSI6PNRCfVl+slNTrjFQXCXXpCfgKJF8J/U+gj9HYM5RoFrB4xgDL8YZfFYmBhiTZzL6vjv9MZm+slngHuGWXDcu1avvniKtbl+iTunrG+ZB2nr6I+QGaLYLzDUv9441RxmvXWUh0cpnZQrlRjkdp3BM9LgVHpBrbi8ttDdU2ba+wlUYejwgj/W/OUll8CNLJRN50Clm+4smmXtHaAe/DxI/nt3TdcBRn76WZkex+zKl3AnXrSzP57gipfQDWXAcRkOC6wt1uPOOau3eB9i8Q8CFDJHjWGmph2G9j5N7fdFtBY2YgY6py6R1YzAhjitaUshNYzOaaM/Bb+sNQ/XnQ5Qymv9bhvzHkjmPJD3VvV8hSX5OnsoBQiDpe/NDj5wi3jfJZfqxcJOH+0VR9Uvw8TRiHo6AQ215ot2WeFNx2k1mDQ+j60IHXdr8VgJk6NuVHDtiicErCozOHLX9OW93zc+VVesRMg=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: daily-questions-config
      namespace: daily-questions
    type: Opaque
# Generated via: 
# kubeseal --scope namespace-wide --namespace daily-questions --controller-namespace bitnami --controller-name sealed-secrets -o yaml < local-config.yaml > kubernetes/secret.yaml